//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryDischarger.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatteryDischarger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accelerate battery discharge: ähnelt.
        /// </summary>
        public static string AccelerateBatteryDischarge {
            get {
                return ResourceManager.GetString("AccelerateBatteryDischarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action when the selected battery charge level is reached: ähnelt.
        /// </summary>
        public static string ActionAtTheSelectedBatteryChargeLevel {
            get {
                return ResourceManager.GetString("ActionAtTheSelectedBatteryChargeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ✔ ähnelt.
        /// </summary>
        public static string CheckCorrect {
            get {
                return ResourceManager.GetString("CheckCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ❌ ähnelt.
        /// </summary>
        public static string CheckIncorrect {
            get {
                return ResourceManager.GetString("CheckIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current battery charge in percent: ähnelt.
        /// </summary>
        public static string CurrentBatteryChargeInPercent {
            get {
                return ResourceManager.GetString("CurrentBatteryChargeInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Did not found a useable WorkingDirectoryPath. ähnelt.
        /// </summary>
        public static string DidNotFoundAUseableWorkingDirectoryPath {
            get {
                return ResourceManager.GetString("DidNotFoundAUseableWorkingDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hibernate device ähnelt.
        /// </summary>
        public static string HibernateDevice {
            get {
                return ResourceManager.GetString("HibernateDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        public static string LanguageColon {
            get {
                return ResourceManager.GetString("LanguageColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legal notice ähnelt.
        /// </summary>
        public static string LegalNotice {
            get {
                return ResourceManager.GetString("LegalNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License code: ähnelt.
        /// </summary>
        public static string LicenseCodeColon {
            get {
                return ResourceManager.GetString("LicenseCodeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More than one battery was detected, which is not supported by the program. ähnelt.
        /// </summary>
        public static string MoreThanOneBatteryWasDetectedWhichIsNotSupportedByTheProgram {
            get {
                return ResourceManager.GetString("MoreThanOneBatteryWasDetectedWhichIsNotSupportedByTheProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No battery was detected. ähnelt.
        /// </summary>
        public static string NoBatteryWasDetected {
            get {
                return ResourceManager.GetString("NoBatteryWasDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of minutes until the selected battery level is reached: ähnelt.
        /// </summary>
        public static string NumberOfMinutesUntilTheSelectedBatteryLevelIsReached {
            get {
                return ResourceManager.GetString("NumberOfMinutesUntilTheSelectedBatteryLevelIsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prevent unwanted system sleep mode: ähnelt.
        /// </summary>
        public static string PreventUnwantedSystemSleepMode {
            get {
                return ResourceManager.GetString("PreventUnwantedSystemSleepMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set device to power saving mode ähnelt.
        /// </summary>
        public static string SetDeviceToPowerSavingMode {
            get {
                return ResourceManager.GetString("SetDeviceToPowerSavingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shut down device ähnelt.
        /// </summary>
        public static string ShutDownDevice {
            get {
                return ResourceManager.GetString("ShutDownDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start controlled discharge ähnelt.
        /// </summary>
        public static string StartControlledDischarge {
            get {
                return ResourceManager.GetString("StartControlledDischarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop controlled discharge ähnelt.
        /// </summary>
        public static string StopControlledDischarge {
            get {
                return ResourceManager.GetString("StopControlledDischarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Structure of the specified license code is not correct. ähnelt.
        /// </summary>
        public static string StructureOfTheSpecifiedLicenseCodeIsNotCorrect {
            get {
                return ResourceManager.GetString("StructureOfTheSpecifiedLicenseCodeIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target battery charge (in percent): ähnelt.
        /// </summary>
        public static string TargetBatteryChargeInPercent {
            get {
                return ResourceManager.GetString("TargetBatteryChargeInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The battery status could not be determined. ähnelt.
        /// </summary>
        public static string TheBatteryStatusCouldNotBeDetermined {
            get {
                return ResourceManager.GetString("TheBatteryStatusCouldNotBeDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The device may still be charging or the battery status could not be determined. 
        ///The controlled battery discharge process is nevertheless carried out normally. ähnelt.
        /// </summary>
        public static string TheDeviceMayStillBeChargingOrTheBatteryStatusCouldNotBeDetermined {
            get {
                return ResourceManager.GetString("TheDeviceMayStillBeChargingOrTheBatteryStatusCouldNotBeDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The license code is not valid. ähnelt.
        /// </summary>
        public static string TheLicenseCodeIsNotValid {
            get {
                return ResourceManager.GetString("TheLicenseCodeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The operating system is not supported. ähnelt.
        /// </summary>
        public static string TheOperatingSystemIsNotSupported {
            get {
                return ResourceManager.GetString("TheOperatingSystemIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The program can be used only after a valid license code has been entered. ähnelt.
        /// </summary>
        public static string TheProgramCanBeUsedOnlyAfterAValidLicenseCodeHasBeenEntered {
            get {
                return ResourceManager.GetString("TheProgramCanBeUsedOnlyAfterAValidLicenseCodeHasBeenEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verify ähnelt.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
    }
}
