//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryDischarger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatteryDischarger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerate battery discharge:.
        /// </summary>
        public static string AccelerateBatteryDischarge {
            get {
                return ResourceManager.GetString("AccelerateBatteryDischarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action when the selected battery charge level is reached:.
        /// </summary>
        public static string ActionAtTheSelectedBatteryChargeLevel {
            get {
                return ResourceManager.GetString("ActionAtTheSelectedBatteryChargeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✔.
        /// </summary>
        public static string CheckCorrect {
            get {
                return ResourceManager.GetString("CheckCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌.
        /// </summary>
        public static string CheckIncorrect {
            get {
                return ResourceManager.GetString("CheckIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current battery charge in percent:.
        /// </summary>
        public static string CurrentBatteryChargeInPercent {
            get {
                return ResourceManager.GetString("CurrentBatteryChargeInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not found a useable WorkingDirectoryPath..
        /// </summary>
        public static string DidNotFoundAUseableWorkingDirectoryPath {
            get {
                return ResourceManager.GetString("DidNotFoundAUseableWorkingDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        public static string DoNothing {
            get {
                return ResourceManager.GetString("DoNothing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate device.
        /// </summary>
        public static string HibernateDevice {
            get {
                return ResourceManager.GetString("HibernateDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LanguageColon {
            get {
                return ResourceManager.GetString("LanguageColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal notice.
        /// </summary>
        public static string LegalNotice {
            get {
                return ResourceManager.GetString("LegalNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License code:.
        /// </summary>
        public static string LicenseCodeColon {
            get {
                return ResourceManager.GetString("LicenseCodeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one battery was detected, which is not supported by the program..
        /// </summary>
        public static string MoreThanOneBatteryWasDetectedWhichIsNotSupportedByTheProgram {
            get {
                return ResourceManager.GetString("MoreThanOneBatteryWasDetectedWhichIsNotSupportedByTheProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No battery was detected..
        /// </summary>
        public static string NoBatteryWasDetected {
            get {
                return ResourceManager.GetString("NoBatteryWasDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of minutes until the selected battery level is reached:.
        /// </summary>
        public static string NumberOfMinutesUntilTheSelectedBatteryLevelIsReached {
            get {
                return ResourceManager.GetString("NumberOfMinutesUntilTheSelectedBatteryLevelIsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent unwanted system sleep mode:.
        /// </summary>
        public static string PreventUnwantedSystemSleepMode {
            get {
                return ResourceManager.GetString("PreventUnwantedSystemSleepMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set device to power saving mode.
        /// </summary>
        public static string SetDeviceToPowerSavingMode {
            get {
                return ResourceManager.GetString("SetDeviceToPowerSavingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut down device.
        /// </summary>
        public static string ShutDownDevice {
            get {
                return ResourceManager.GetString("ShutDownDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start controlled discharge.
        /// </summary>
        public static string StartControlledDischarge {
            get {
                return ResourceManager.GetString("StartControlledDischarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop controlled discharge.
        /// </summary>
        public static string StopControlledDischarge {
            get {
                return ResourceManager.GetString("StopControlledDischarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure of the specified license code is not correct..
        /// </summary>
        public static string StructureOfTheSpecifiedLicenseCodeIsNotCorrect {
            get {
                return ResourceManager.GetString("StructureOfTheSpecifiedLicenseCodeIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target battery charge (in percent):.
        /// </summary>
        public static string TargetBatteryChargeInPercent {
            get {
                return ResourceManager.GetString("TargetBatteryChargeInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The battery status could not be determined..
        /// </summary>
        public static string TheBatteryStatusCouldNotBeDetermined {
            get {
                return ResourceManager.GetString("TheBatteryStatusCouldNotBeDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device may still be charging or the battery status could not be determined.
        ///The controlled battery discharge process is nevertheless carried out normally..
        /// </summary>
        public static string TheDeviceMayStillBeChargingOrTheBatteryStatusCouldNotBeDetermined {
            get {
                return ResourceManager.GetString("TheDeviceMayStillBeChargingOrTheBatteryStatusCouldNotBeDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license code is not valid..
        /// </summary>
        public static string TheLicenseCodeIsNotValid {
            get {
                return ResourceManager.GetString("TheLicenseCodeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operating system is not supported..
        /// </summary>
        public static string TheOperatingSystemIsNotSupported {
            get {
                return ResourceManager.GetString("TheOperatingSystemIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program can be used only after a valid license code has been entered..
        /// </summary>
        public static string TheProgramCanBeUsedOnlyAfterAValidLicenseCodeHasBeenEntered {
            get {
                return ResourceManager.GetString("TheProgramCanBeUsedOnlyAfterAValidLicenseCodeHasBeenEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
    }
}
